//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Duties
    {
        public tb_Duties()
        {
            this.tb_Users = new HashSet<tb_Users>();
        }
    
        public long DutyID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public long DepartID { get; set; }
    
        public virtual tb_Departs tb_Departs { get; set; }
        public virtual ICollection<tb_Users> tb_Users { get; set; }
    }
}
