//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Departs
    {
        public tb_Departs()
        {
            this.tb_SalesPlan = new HashSet<tb_SalesPlan>();
            this.tb_Duties = new HashSet<tb_Duties>();
            this.tb_Users = new HashSet<tb_Users>();
        }
    
        public long DepartID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<long> ParentNode { get; set; }
        public string Authority { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<tb_SalesPlan> tb_SalesPlan { get; set; }
        public virtual ICollection<tb_Duties> tb_Duties { get; set; }
        public virtual ICollection<tb_Users> tb_Users { get; set; }
    }
}
