//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Menus_Left
    {
        public long MenuID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<long> ParentNode { get; set; }
        public string HtmlAdress { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
