//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SalesRecord
    {
        public long ID { get; set; }
        public long ClientID { get; set; }
        public long UserID { get; set; }
        public string Mode { get; set; }
        public string Num { get; set; }
        public long ProductID { get; set; }
        public string Price { get; set; }
        public string Amount { get; set; }
        public string Total { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public string Content { get; set; }
        public string Remarks { get; set; }
    
        public virtual tb_Clients tb_Clients { get; set; }
        public virtual tb_Products tb_Products { get; set; }
        public virtual tb_Users tb_Users { get; set; }
    }
}
