//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ServiceRecord
    {
        public long ID { get; set; }
        public long ClientID { get; set; }
        public long UserID { get; set; }
        public string Mode { get; set; }
        public string CostEstimate { get; set; }
        public Nullable<System.DateTime> BeginTimeDate { get; set; }
        public Nullable<System.DateTime> EndTimeDate { get; set; }
        public string Content { get; set; }
        public string Satisfaction { get; set; }
        public string Feedback { get; set; }
        public string ServiceReamarks { get; set; }
    
        public virtual tb_Clients tb_Clients { get; set; }
        public virtual tb_Users tb_Users { get; set; }
    }
}
