//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Suppliers
    {
        public tb_Suppliers()
        {
            this.tb_Products = new HashSet<tb_Products>();
        }
    
        public long SupplierID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string SPhone { get; set; }
        public string Fax { get; set; }
        public string Area { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
        public string AccountBank { get; set; }
        public string BankAccount { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tb_Products> tb_Products { get; set; }
    }
}
